### ISSUE TITLE
Node availability

### ISSUE THREAD

**Issue by blondviper** [ikzelf/zbx_kubernetes#1]
can I monitor node availability with this template?
where should I paste .json file? 

thanks for help

**Comment by ikzelf** [comment]
Hi, I almost forgot about your message. Sorry for that. These scripts are just delivering data that can be fed into zabbix. The zbx_k8s_metrics.py script also does the sending to zabbix. The zbx_k8s_lld.py does not send data but this can easily be added, if needed.

For node availability you can create a nodata trigger on an item that should alway get fresh data within the 'nodata period'. If that data did not arrive in that time, the node won't be there or at least not be able to send data to zabbix.

**Comment by ikzelf** [comment]
did you get this any further?

**Comment by blondviper** [comment]
actually no, I've created shell script and used user parameters to retrieve node status

**Comment by ikzelf** [comment]
OK, good for you.
